metatag.metatag_tag.rhd_taxonomy_page_sub_type:
  type: label
  label: 'Red Hat: Page Sub Type Taxonomy'
metatag.metatag_tag.rhd_taxonomy_product:
  type: label
  label: 'Red Hat: Product'
metatag.metatag_tag.rhd_taxonomy_product_line:
  type: label
  label: 'Red Hat: Product Line'
metatag.metatag_tag.rhd_taxonomy_topic:
  type: label
  label: 'Red Hat: Topic'
metatag.metatag_tag.rhd_node_type:
  type: label
  label: 'Red Hat: Node Type'
