baseURL = "https://redhat-developer.github.io/rhd-frontend/"
languageCode = "en-us"
title = "RHD Front-end Code and Documentation"
theme = "rhd"
publishDir = "../../docs"
canonifyURLs = true

[params]
    Minify = false