# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  # - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
  #   label: "Post" # Used in the UI, ie.: "New Post"
  #   folder: "_posts" # The path to the folder where the documents are stored
  #   sort: "date:desc" # Default is title:asc
  #   create: false # Allow users to create new Posts in the admin UI
  #   slug: "{{month}}-{{day}}-{{year}}-{{slug}}"
  #   fields: # The fields each document in this collection have
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
  #     - {label: "Title", name: "title", widget: "string", tagname: "h1"}
  #     - label: "Author"
  #       name: "author"
  #       widget: "select"
  #       options:
  #         - { label: "Adam Jolicoeur", value: "adam_jolicoeur" }
  #     - {label: "Publish Date", name: "date", widget: "datetime", format: "MM-DD-YYYY HH:mm:ss"}
  #     - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
  #     - {label: "Body", name: "body", widget: "markdown", required: false}
  #     - {label: "Categories", name: "categories", widget: "string", required: false}
  # COMPONENTS
  # - name: "components"
  #   label: "Components"
  #   folder: "pages/components"
  #   sort: "title:asc"
  #   create: false # Allow users to create new Components in the admin UI
  #   slug: "{{slug}}"
  #   fields:
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
  #     - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
  #     - {label: "Permalink", name: "permalink", widget: "string", required: true}
  #     - {label: "Section", name: "section", widget: "string", default: "{{State the area that you'd like this to live under}}"}
  #     - {label: "Category", name: "category", width: "string", default: "components", required: true}
  #     - {label: "Status", name: "status", width: "string", default: "{{ set released or unreleased }}", required: true}
  #     - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
  #     - {label: "Body", name: "body", widget: "code", required: true}
  # PAGES
  - name: "page"
    label: "overview-pages"
    folder: "pages"
    sort: "title:asc"
    create: true # Allow users to create new Overview Pages in the admin UI
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Permalink", name: "permalink", widget: "string", required: true}
      - {label: "Section", name: "section", widget: "string", default: "{{State the area that you'd like this to live under}}", required: false}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}
  - name: "design-subpages"
    label: "Design Pages"
    folder: "pages/design"
    sort: "title:asc"
    create: true # Allow users to create new Design pages in the admin UI
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Permalink", name: "permalink", widget: "string", required: true}
      - {label: "Section", name: "section", widget: "string", default: "{{State the area that you'd like this to live under}}"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}
  - name: "gettingstartedsubpages"
    label: "getting-started-pages"
    folder: "pages/getting-started"
    sort: "title:asc"
    create: true # Allow users to create new Getting Started pages in the admin UI
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Permalink", name: "permalink", widget: "string", required: true}
      - {label: "Section", name: "section", widget: "string", default: "{{State the area that you'd like this to live under}}"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}
  - name: "pagessubpages"
    label: "page-example-pages"
    folder: "pages/pages"
    sort: "title:asc"
    create: true # Allow users to create new Page example pages in the admin UI
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Permalink", name: "permalink", widget: "string", required: true}
      - {label: "Section", name: "section", widget: "string", default: "{{State the area that you'd like this to live under}}"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}
  - name: "examplesubpages"
    label: "example-pages"
    folder: "pages/examples"
    sort: "title:asc"
    create: true # Allow users to create new Example pages in the admin UI
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Permalink", name: "permalink", widget: "string", required: true}
      - {label: "Section", name: "section", widget: "string", default: "{{State the area that you'd like this to live under}}"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}
  # Navigation
  - name: "options"
    label: "Navigations"
    editor:
      preview: true
    files:
      - label: "Main Navigation"
        name: "nav"
        file: "_data/navigation.yml"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Name", name: name, widget: string}
              - {label: URL, name: url, widget: string}
              - {label: "Title", name: title, width: string}
      - label: "Assemblies Page Navigation"
        name: "assemblies-nav"
        file: "_data/assemblies.yml"
        fields:
          - label: "Assemblies Page Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Name", name: name, widget: string}
              - {label: URL, name: url, widget: string}
              - {label: "Title", name: title, width: string}
